// Code generated by heygen-cli/codegen. DO NOT EDIT.

package gen

import "github.com/heygen-com/heygen-cli/internal/command"

func intPtr(v int) *int { return &v }

// Groups maps group name → slice of command specs.
// Used by the command builder to register generated commands.
var Groups = map[string][]*command.Spec{
	"upload": {
		UploadCreate,
	},
	"widget": {
		WidgetActivateCreate,
		WidgetCreate,
		WidgetDelete,
		WidgetGet,
		WidgetList,
	},
}
