// Code generated by heygen-cli/codegen. DO NOT EDIT.

package gen

import "github.com/heygen-com/heygen-cli/internal/command"

var UploadCreate = &command.Spec{
	Group:        "upload",
	Name:         "create",
	Summary:      "Upload a file",
	Description:  "",
	Endpoint:     "/v3/uploads",
	Method:       "POST",
	BodyEncoding: "multipart",
	Flags: []command.FlagSpec{
		{
			Name:     "file",
			Type:     "string",
			Default:  "",
			Help:     "File to upload",
			Required: true,
			Enum:     nil,
			Min:      nil,
			Max:      nil,
			Source:   "file",
			JSONName: "file",
		},
	},
}
