// Code generated by heygen-cli/codegen. DO NOT EDIT.

package gen

import "github.com/heygen-com/heygen-cli/internal/command"

var UploadUpload = &command.Spec{
	Group:        "upload",
	Name:         "upload",
	Summary:      "Upload a file",
	Description:  "",
	Endpoint:     "/v3/uploads",
	Method:       "POST",
	BodyEncoding: "multipart",
	DataField:    "data",
	Examples: []string{
		"heygen upload upload ./file.txt",
	},
	Args: []command.ArgSpec{
		{Name: "file", Target: "file", Param: "file", Help: "File path for upload"},
	},
}
