// Code generated by heygen-cli/codegen. DO NOT EDIT.

package gen

import "github.com/heygen-com/heygen-cli/internal/command"

var WidgetActivate = &command.Spec{
	Group:        "widget",
	Name:         "activate",
	Summary:      "Activate a widget",
	Description:  "",
	Endpoint:     "/v3/widgets/{widget_id}/activate",
	Method:       "POST",
	BodyEncoding: "json",
	Examples: []string{
		"heygen widget activate <widget-id>",
	},
	Args: []command.ArgSpec{
		{Name: "widget-id", Target: "path", Param: "widget_id", Help: "Widget ID"},
	},
	Flags: []command.FlagSpec{
		{
			Name:     "force",
			Type:     "bool",
			Default:  "false",
			Help:     "Force activation",
			Required: false,
			Enum:     nil,
			Min:      nil,
			Max:      nil,
			Source:   "body",
			JSONName: "force",
		},
	},
}

var WidgetCreate = &command.Spec{
	Group:        "widget",
	Name:         "create",
	Summary:      "Create a widget",
	Description:  "",
	Endpoint:     "/v3/widgets",
	Method:       "POST",
	BodyEncoding: "json",
	Examples: []string{
		"heygen widget create --name 'My Widget'",
	},
	Flags: []command.FlagSpec{
		{
			Name:     "color",
			Type:     "string",
			Default:  "",
			Help:     "Widget color",
			Required: false,
			Enum:     nil,
			Min:      nil,
			Max:      nil,
			Source:   "body",
			JSONName: "color",
		},
		{
			Name:     "count",
			Type:     "int",
			Default:  "",
			Help:     "Widget count",
			Required: false,
			Enum:     nil,
			Min:      intPtr(1),
			Max:      intPtr(100),
			Source:   "body",
			JSONName: "count",
		},
		{
			Name:     "name",
			Type:     "string",
			Default:  "",
			Help:     "Widget name",
			Required: true,
			Enum:     nil,
			Min:      nil,
			Max:      nil,
			Source:   "body",
			JSONName: "name",
		},
		{
			Name:     "tags",
			Type:     "string-slice",
			Default:  "",
			Help:     "Widget tags",
			Required: false,
			Enum:     nil,
			Min:      nil,
			Max:      nil,
			Source:   "body",
			JSONName: "tags",
		},
	},
}

var WidgetDelete = &command.Spec{
	Group:        "widget",
	Name:         "delete",
	Summary:      "Delete a widget",
	Description:  "",
	Endpoint:     "/v3/widgets/{widget_id}",
	Method:       "DELETE",
	BodyEncoding: "",
	Examples: []string{
		"heygen widget delete <widget-id>",
	},
	Args: []command.ArgSpec{
		{Name: "widget-id", Target: "path", Param: "widget_id", Help: "Widget ID"},
	},
}

var WidgetGet = &command.Spec{
	Group:        "widget",
	Name:         "get",
	Summary:      "Get widget details",
	Description:  "",
	Endpoint:     "/v3/widgets/{widget_id}",
	Method:       "GET",
	BodyEncoding: "",
	Examples: []string{
		"heygen widget get <widget-id>",
	},
	Args: []command.ArgSpec{
		{Name: "widget-id", Target: "path", Param: "widget_id", Help: "Widget ID"},
	},
}

var WidgetList = &command.Spec{
	Group:        "widget",
	Name:         "list",
	Summary:      "List widgets",
	Description:  "",
	Endpoint:     "/v3/widgets",
	Method:       "GET",
	BodyEncoding: "",
	TokenField:   "next_token",
	DataField:    "data",
	Examples: []string{
		"heygen widget list --limit 10",
	},
	Flags: []command.FlagSpec{
		{
			Name:     "limit",
			Type:     "int",
			Default:  "10",
			Help:     "Max results per page",
			Required: false,
			Enum:     nil,
			Min:      intPtr(1),
			Max:      intPtr(100),
			Source:   "query",
			JSONName: "limit",
		},
		{
			Name:     "status",
			Type:     "string",
			Default:  "",
			Help:     "Filter by status",
			Required: false,
			Enum:     []string{"active", "archived"},
			Min:      nil,
			Max:      nil,
			Source:   "query",
			JSONName: "status",
		},
	},
}
